version: '3'
services:
  web:
    build: .
    ports:
      - "${PRO_APP_PORT}:${PRO_APP_PORT}"
    environment:
      - NODE_ENV=development
      - PRO_APP_PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
